name: Continuous Integration
on:
  push:
    branches:
      - main
      - actions-*
    tags:
      - v*
  pull_request:
env:
  BUNDLE_CLEAN: "true"
  BUNDLE_PATH: vendor/bundle
  BUNDLE_JOBS: 3
  BUNDLE_RETRY: 3
jobs:
  specs:
    name: ruby-${{ matrix.ruby }} ${{ matrix.appraisal }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "ruby"
            standardrb: true
          - ruby: "ruby"
            appraisal: "without_activesupport"
          - ruby: "3.2"
            appraisal: "activesupport_7"
          - ruby: "3.0"
            appraisal: "activesupport_6"
          - ruby: "2.6"
            appraisal: "activesupport_5"
          - ruby: "2.5"
            appraisal: "activesupport_4"
            bundler: "1.17.3"
            gemfile: gemfiles/activesupport_4.gemfile
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup bundler
        if: matrix.bundler != ''
        run: |
          gem uninstall bundler --all
          gem install bundler --no-document --version ${{ matrix.bundler }}
      - name: Set Appraisal bundle
        if: matrix.appraisal != '' && matrix.gemfile == ''
        run: |
          echo "using gemfile gemfiles/${{ matrix.appraisal }}.gemfile"
          bundle config set gemfile "gemfiles/${{ matrix.appraisal }}.gemfile"
          cat gemfiles/${{ matrix.appraisal }}.gemfile
      - name: Install bundle
        run: |
          bundle update
      - name: Run specs
        run:  bundle exec rake spec
      - name: Run standardrb
        if:   matrix.standardrb == true
        run:  bundle exec rake standard
